### ISSUE TITLE
Nextmeeting shows meeting info even if the date is passed

### ISSUE THREAD

**Issue by wolfskyzen** [wolfskyzen/vfcommsbotpy#8]
If the currently set meeting date has already passed, /nextmeeting still shows the meeting and an incorrect time. (It assumes the next meeting is the same date and does a delta on hours and minutes.)

> The next meeting is Sunday, September 10, 2017, 02:00 PM at House. That is in 17 hours and 10 minutes.
Triggered on September 13th at 8:50 PM.

This should just say the meeting is not set and try to internally clear the next meeting data.

**Comment by wolfskyzen** [comment]
This may become invalided by #2

**Comment by Maxwolf** [comment]
Added a check to this so if a date gets in there that is in the past it will properly display this.

`
The next meeting is Sunday, September 10, 2017, 02:00 PM at guys house. The next meeting date is in the past.`
